	db "Master Ball@"
	db "Ultra Ball@"
	db "Luminpolvere@"
	db "Mega Ball@"
	db "# Ball@"
	db "Premier Ball@"
	db "Bicicletta@"
	db "Pietralunare@"
	db "Antidoto@"
	db "Antiscottat.@"
	db "Antigelo@"
	db "Sveglia@"
	db "Antiparalisi@"
	db "Ricarica Tot@"
	db "Pozione Max@"
	db "Iperpozione@"
	db "Superpozione@"
	db "Pozione@"
	db "Fune di fuga@"
	db "Repellente@"
	db "Elisir Max@"
	db "Pietrafocaia@"
	db "Pietratuono@"
	db "Pietraidrica@"
	db "Velenguardia@"
	db "PS Su@"
	db "Proteina@"
	db "Ferro@"
	db "Carburante@"
	db "Fortunpugno@"
	db "Calcio@"
	db "Caram. Rara@"
	db "Precisione X@"
	db "Pietrafoglia@"
	db "Metalpolvere@"
	db "Pepita@"
	db "#bambola@"
	db "Cura Totale@"
	db "Revitaliz.@"
	db "Revital. Max@"
	db "Superguardia@"
	db "Superrepel.@"
	db "Repel. Max@"
	db "Supercolpo@"
	db "Fuocoguardia@"
	db "Acqua Fresca@"
	db "Gassosa@"
	db "Lemonsucco@"
	db "Attacco X@"
	db "Geloguardia@"
	db "Difesa X@"
	db "Velocità X@"
	db "Special X@"
	db "Salvadanaio@"
	db "Detector@"
	db "#flauto@"
	db "Condiv. Esp.@"
	db "Amo Vecchio@"
	db "Amo Buono@"
	db "Fogliargento@"
	db "Super Amo@"
	db "PP Su@"
	db "Etere@"
	db "Etere Max@"
	db "Elisir@"
	db "Squama Rossa@"
	db "Poz. Segreta@"
	db "Bigl. Nave@"
	db "Uovo Ignoto@"
	db "Camp. Chiara@"
	db "Aladargento@"
	db "Latte Mumu@"
	db "Rapidartigli@"
	db "Baccapesca@"
	db "Fogliadoro@"
	db "Sabbiasoff.@"
	db "Beccaffilato@"
	db "Baccaliegia@"
	db "Baccaperina@"
	db "Baccafrago@"
	db "Velenaculeo@"
	db "Roccia di Re@"
	db "Baccaki@"
	db "Baccastagna@"
	db "Ghic. Rossa@"
	db "Minifungo@"
	db "Grande Fungo@"
	db "Argenpolvere@"
	db "Ghicocca Blu@"
	db "Ipnoguardia@"
	db "Monetamuleto@"
	db "Ghic. Gialla@"
	db "Ghic. Verde@"
	db "Velopuro@"
	db "Acqua Magica@"
	db "Cucch. Torto@"
	db "Ghicocca Bnc@"
	db "Cinturanera@"
	db "Ghicoc. Nera@"
	db "Paraguardia@"
	db "Ghicoc. Rosa@"
	db "Occhialineri@"
	db "Codaslowpoke@"
	db "Fiocco Rosa@"
	db "Gambo@"
	db "Pallafumo@"
	db "Gelomai@"
	db "Calamita@"
	db "Baccaprugna@"
	db "Perla@"
	db "Grande Perla@"
	db "Pietrastante@"
	db "Spettrotarga@"
	db "Iramella@"
	db "GS Ball@"
	db "Carta Blu@"
	db "Miracolseme@"
	db "Ossospesso@"
	db "Bandana@"
	db "Confuguardia@"
	db "Polvenergia@"
	db "Radicenergia@"
	db "Polvocura@"
	db "Vitalerba@"
	db "Pietradura@"
	db "Fortunuovo@"
	db "Apriporta@"
	db "Pezzo Mecc.@"
	db "Bigl. Uovo@"
	db "Bamb. Persa@"
	db "Polvostella@"
	db "Pezzo Stella@"
	db "Chiave Sott.@"
	db "Abbonamento@"
	db "Helixfossile@"
	db "Domofossile@"
	db "Ambra Antica@"
	db "Carbonella@"
	db "Succodibacca@"
	db "Mirino@"
	db "Pacco di Oak@"
	db "Vigorerba@"
	db "Metalcoperta@"
	db "Dentedidrago@"
	db "Amicamuleto@"
	db "Avanzi@"
	db "Ricerche@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Baccamela@"
	db "Squama Drago@"
	db "Gene Furioso@"
	db "Teru-sama@"
	db "Dif. Sp. X@"
	db "Teru-sama@"
	db "Ceneremagica@"
	db "Ferropalla@"
	db "Mess. Fiore@"
	db "Level Ball@"
	db "Esca Ball@"
	db "Rapid Ball@"
	db "Teru-sama@"
	db "Elettropalla@"
	db "Friend Ball@"
	db "Luna Ball@"
	db "Love Ball@"
	db "Scat. Norm.@"
	db "Scat. Lusso@"
	db "Pietrasolare@"
	db "Fiocco Pois@"
	db "Teru-sama@"
	db "Upgrade@"
	db "Baccarancia@"
	db "Baccacedro@"
	db "Annaffiatoio@"
	db "Teru-sama@"
	db "Parco Ball@"
	db "Ala d'Iride@"
	db "Teru-sama@"
	db "Mattoncino@"
	db "Mess. Surf@"
	db "Mess. Azzur.@"
	db "Mess.Ritrat.@"
	db "Mess. Dolce@"
	db "Mess. Eone@"
	db "Mess. Morphe@"
	db "Mess. Cielo@"
	db "Mess. Musica@"
	db "Mess. Vision@"
	db "Teru-sama@"
	db "MT01@"
	db "MT02@"
	db "MT03@"
	db "MT04@"
	db "Teru-sama@"
	db "MT05@"
	db "MT06@"
	db "MT07@"
	db "MT08@"
	db "MT09@"
	db "MT10@"
	db "MT11@"
	db "MT12@"
	db "MT13@"
	db "MT14@"
	db "MT15@"
	db "MT16@"
	db "MT17@"
	db "MT18@"
	db "MT19@"
	db "MT20@"
	db "MT21@"
	db "MT22@"
	db "MT23@"
	db "MT24@"
	db "MT25@"
	db "MT26@"
	db "MT27@"
	db "MT28@"
	db "Teru-sama@"
	db "MT29@"
	db "MT30@"
	db "MT31@"
	db "MT32@"
	db "MT33@"
	db "MT34@"
	db "MT35@"
	db "MT36@"
	db "MT37@"
	db "MT38@"
	db "MT39@"
	db "MT40@"
	db "MT41@"
	db "MT42@"
	db "MT43@"
	db "MT44@"
	db "MT45@"
	db "MT46@"
	db "MT47@"
	db "MT48@"
	db "MT49@"
	db "MT50@"
	db "MN01@"
	db "MN02@"
	db "MN03@"
	db "MN04@"
	db "MN05@"
	db "MN06@"
	db "MN07@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "?@"
